### ISSUE TITLE
General Discussions

### ISSUE THREAD

**Issue by Polaris000** [Polaris000/Chaoss_19_Microtasks#10]

**Comment by Polaris000** [comment]
Hey @valeriocos @aswanipranjal! I was wondering when the microtasks will be reviewed...

Let me know thanks!

**Comment by aswanipranjal** [comment]
We are going trough the tasks @Polaris000. We will let you know in case we have any comments or need clarification

**Comment by Polaris000** [comment]
@jgbarah @valeriocos @aswanipranjal 
My finals end on the 14th of May and I will be free to work on this project from the morning (IST) of 16th May. (It will take me most of 15th to reach home from University). 

- It would be great if we could have an IRC chat in the next two-three days regarding the project plan, if it is convenient for all of you. What do you say?

- It would be great if you could give a more in depth review of [microtask6](https://github.com/Polaris000/Chaoss_19_Microtasks/tree/master/microtask6) so everything is as planned and it does n't waste time later on deciding on the exact format/structure of each implementation. Things like a complete OOP structure (rather than both OOP and regular code as done [here](https://github.com/chaoss/wg-evolution/blob/master/implementations/Code_Changes-Git.ipynb)), the use of bash commands in Jupyter notebooks and the amount of documentation and comments can be discussed. Do you think this is a good idea? 

- Also, once I reach home (16th of May), I thought it would be a good idea to make a document for an unimplemented metric (so that the finished document looks something like [this](https://github.com/chaoss/wg-evolution/blob/master/metrics/Code_Changes.md)) and you can give me reviews on that. What do you think?

In the IRC chat, we could discuss things like tracking progress (via blog posts, etc.), milestones, etc. 

If there is anything else I should be aware of, please let me know. 
If a meeting has already been planned, please let me know when it would take place. 

I am open to any kind of feedback/constructive criticism and would love to improve upon the points you suggest. 

Thanks!
